### ISSUE TITLE
Add "Settings" menu entry (M-Droid app settings)

### ISSUE THREAD

**Issue by ghost** [SkyzohKey/M-Droid#11]
- [x] Home (main screen)
- [x] Repositories
- [ ] Interface
  - Language
  - Theme
  - ...
- [ ] Network
  - Updating / Autoupdating
  - Limit to WiFi
  - ...
- ...

**Comment by SkyzohKey** [comment]
The navigation Drawer isn't intended to receive settings. Instead, settings will have owns screen(s). That's planed and will be released within the next releases 😃 
  
The only "issue" yet is that I have no idea how i'll design the said screen(s) c:

**Comment by SkyzohKey** [comment]
Eheh, shaping it !

![](https://i.imgur.com/VbsnUn3.png)
