### ISSUE TITLE
UI Enahncement - Lists instead of tiles as an option

### ISSUE THREAD

**Issue by aproposnix** [SkyzohKey/M-Droid#20]
One of the things I liked about the old version of F-Droid was that it was easy to scrol through apps (esp., based on categories like 'Recently Updated" or 'What's New').... When they moved to showing only tiles it became chaotic and confusing.  Though m-droid is way better looking than F-Droid,, it's also using the tiles instead of lists (with the exception of the search result list which is exactly what I would like to see as the standard view). 

It would be nice to have an option to switch to either list view (like you see on the search results) or the tiles (which is the default view currently).

**Comment by SkyzohKey** [comment]
That's planed, such feature is easy to implement and will be implemented soon.
