### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [SkyzohKey/M-Droid#23]
It would be useful to have this app on the F-Droid catalogue itself. Is it doable?

**Comment by rugk** [comment]
Obviously, this needs to be done…

A little meta, but well… no-one finds that client otherwise. (Also remember F-Droid is on F-Droid.)

So this would also bring auto-self-updates.

**Comment by nicolasmaia** [comment]
@rudloff might be able to help with that.

**Comment by Rudloff** [comment]
I don't see any show-stopper here (except that React Native apps require a bit more work to package).
Can you please open a RFP?

**Comment by nicolasmaia** [comment]
Done: https://gitlab.com/fdroid/rfp/issues/816

**Comment by IzzySoft** [comment]
Unfortunately has an issue, reported by the "scanner bot":

    ERROR: Found unknown maven repo '$rootDir/../node_modules/react-native/android' at android/build.gradle

That Maven repo is not whitelisted. Not being a dev, I'm not sure how to fix this issue; including the code as sub-module instead of using the Maven repo? @Rudloff?

**Comment by Rudloff** [comment]
React Native apps all use a local Maven repository containing the React libraries, so this is not a real problem (we usually whitelist it in the build recipe).

**Comment by IzzySoft** [comment]
Ah, good to know (I hope I don't forget that when it comes up next). So where is the RFP stuck then?

PS: Until the RFP was successfully processed, I've just added M-Droid to my repo.

**Comment by Bubu** [comment]
Just merged this.

**Comment by IzzySoft** [comment]
Thanks @Bubu – didn't expect it *that* fast :+1: So it should show up in the official repo soon (and then will be removed from my repo, to avoid confusion).

**Comment by krombel** [comment]
It is already part of F-Droid.
Have a look here: https://f-droid.org/en/packages/com.mdroid/

**Comment by IzzySoft** [comment]
@krombel yes, as Bubu wrote above ("Just merged this" referred to the RFP being completed) :smiley:

In other words: @picsi can close this issue :+1:

Though it would be nice if @SkyzohKey could provide some screenshots via "fastlane mode" in this repo here (see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) for details – fastlane itself isn't needed, just setup the `metadata` directory as shown in the first "graphic" with the parts you want to provide, e.g. `metadata/en/phoneScreenshots/*.jpg`) so we get some visuals… :pray:
