### ISSUE TITLE
Main screen scroll stutters

### ISSUE THREAD

**Issue by Madis0** [SkyzohKey/M-Droid#4]
On a high-end device, running Android 8.1. Perhaps it tries to load all icons on scroll, including those that are hidden on a row?

**Comment by SkyzohKey** [comment]
Yep it does, but this will be fixed in the next release by using `FlatList` to displays `AppsList` components instead of a `ScrollView`. Basically `FlatList` does render only what is shown on the screen, where `ScrollView` renders every childrens even if they are not visible on the screen.
