### ISSUE TITLE
Notification bar should use a darker shade than top bar 

### ISSUE THREAD

**Issue by Madis0** [SkyzohKey/M-Droid#6]
This is Android after all 😉

**Comment by SkyzohKey** [comment]
Needs more informations, what's the issue?

**Comment by Madis0** [comment]
[This might help you understand. ](https://material.io/guidelines/style/color.html) What you are doing now is using the same color on top bar and notification bar, like iOS.

**Comment by SkyzohKey** [comment]
Oh, that's already fixed by 4 releases by now c:

**Comment by Madis0** [comment]
It should use a darker shade of pink, not gray though. #C2185B would be nice.

**Comment by SkyzohKey** [comment]
Yeah but removed because it broke some shady configs running exposed aswell as devices under android 5.1 :/
